config/routes.rb
Rails.application.routes.draw do

  resources :documents

  resources :authors

  resources :comments

  root 'welcome#index'

  get 'import', to: 'welcome#import'
  post 'upload', to: 'welcome#upload'

  namespace :api, defaults: { format: :json } do

    scope module: :v1 do
      resources :documents, :only => [:show, :index]
      resources :authors, :only => [:show, :index]
      resources :comments , :only => [:show, :index]
    end

  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :first_name, presence: true

  has_many :documents, dependent: :destroy

  def full_name
     "#{first_name} #{last_name}"
  end

  scope :filter_by_email, lambda {|keyword|
    where("email LIKE ?", "%#{keyword}%")
  }

  scope :filter_by_name, lambda {|keyword|
    where("lower(first_name) LIKE ? OR lower(last_name) LIKE ?", "%#{keyword.downcase}%","%#{keyword.downcase}%")
  }

  def self.search(params = {})

    authors = params[:author_ids].present? ? Author.where(id: params[:author_ids]) : Author.all

    authors = authors.filter_by_email(params[:email]) if params[:email]
    authors = authors.filter_by_name(params[:name]) if params[:name]

    authors
  end

end

app/controllers/api/v1/authors_controller.rb
class Api::V1::AuthorsController < ApplicationController
  respond_to :json

  def show
    respond_with Author.find(params[:id])
  end

  def index
    params[:per_page] = 10 unless params[:per_page]
    items = Author.search(params).page(params[:page]).per(params[:per_page])
    render json: items, meta: { pagination:
                                   { per_page: params[:per_page],
                                     pages: items.total_pages,
                                     items: items.total_count } }
  end

  def create
    author = Author.new(params_parser)
    if author.save
      render json: author, status: 201, location: [:api, author]
    else
      render json: {errors: author.errors}, status: 422
    end
  end

  def update
    author = Author.find(params[:id])
    if author.update(params_parser)
      render json: author, status: 201, location: [:api, author]
    else
      render json: {errors: author.errors}, status: 422
    end
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy
    head 204
  end

  private
    def params_parser
      params.require(:author).permit(:email, :first_name, :last_name)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:email, :first_name, :last_name)
    end
end

app/helpers/api/v1/authors_helper.rb
module Api::V1::AuthorsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.email %></td>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>