config/routes.rb
Rails.application.routes.draw do

  resources :documents

  resources :authors

  resources :comments

  root 'welcome#index'

  get 'import', to: 'welcome#import'
  post 'upload', to: 'welcome#upload'

  namespace :api, defaults: { format: :json } do

    scope module: :v1 do
      resources :documents, :only => [:show, :index]
      resources :authors, :only => [:show, :index]
      resources :comments , :only => [:show, :index]
    end

  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  validates :title, :id_book, presence: true
  validates :id_book, uniqueness: true

  belongs_to :author
  has_many :comments, dependent: :destroy

  scope :filter_by_title, lambda {|keyword|
    where("lower(title) LIKE ?", "%#{keyword.downcase}%")
  }

  scope :filter_by_book_id, lambda {|keyword|
    where("lower(id_book) LIKE ?", "%#{keyword.downcase}%")
  }

  def self.search(params = {})

    documents = params[:document_ids].present? ? Document.where(id: params[:document_ids]) : Document.all

    documents = documents.filter_by_title(params[:title]) if params[:title]
    documents = documents.filter_by_book_id(params[:id_book]) if params[:id_book]

    documents
  end
end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < ApplicationController
  respond_to :json

  def show
    respond_with Document.find(params[:id])
  end

  def index
    params[:per_page] = 10 unless params[:per_page]
    items = Document.search(params).page(params[:page]).per(params[:per_page])
    render json: items, meta: { pagination:
                                   { per_page: params[:per_page],
                                     pages: items.total_pages,
                                     items: items.total_count } }
  end

  def create
    document = Document.new(params_parser)
    if document.save
      render json: document, status: 201, location: [:api, document]
    else
      render json: {errors: document.errors}, status: 422
    end
  end

  def update
    document = Document.find(params[:id])
    if document.update(params_parser)
      render json: document, status: 201, location: [:api, document]
    else
      render json: {errors: document.errors}, status: 422
    end
  end

  def destroy
    document = Document.find(params[:id])
    document.destroy
    head 204
  end

  private
    def params_parser
      params.require(:document).permit(:title, :body, :tags, :company, :picture, :is_active, :id_book, :author)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :body, :tags, :company, :picture, :is_active, :id_book, :author_id)
    end
end

app/helpers/api/v1/documents_helper.rb
module Api::V1::DocumentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_area :tags %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :id_book %><br>
    <%= f.text_field :id_book %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.select(:author_id,
    options_from_collection_for_select(Author.all, :id, :full_name), {prompt: "Select an Author"}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Tags</th>
      <th>Company</th>
      <th>Picture</th>
      <th>Is active</th>
      <th>Id book</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.body %></td>
        <td><%= document.tags %></td>
        <td><%= document.company %></td>
        <td><%= document.picture %></td>
        <td><%= document.is_active %></td>
        <td><%= document.id_book %></td>
        <td><%= document.author_id %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @document.body %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @document.tags %>
</p>

<p>
  <strong>Company:</strong>
  <%= @document.company %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @document.picture %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @document.is_active %>
</p>

<p>
  <strong>Id book:</strong>
  <%= @document.id_book %>
</p>

<p>
  <strong>Author:</strong>
  <%= @document.author_id %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>